version: "3"

services:
  laravel:
    build: .
    ports:
      - "8444:80"
    volumes:
      - ./api-food/:/var/www/html
    command: bash -c "composer install && php artisan schedule:work"

volumes: 
  mysql_data:
